### ISSUE TITLE
Добавить новые категории 

### ISSUE THREAD

**Issue by shtormnick** [shitikovkirill/RentalEmber#2]
Добавить новые критерии поиска , такие как :
этажность дома , 
конструкция дома (бетонный ,пеноблок,блочный ,кирпичный), 
квадратура квартиры, дома (общая квадратура, жилая квадратура)
убрать поле "владелец" заменить на"период постройки"(новострой,вторострой, сталинка, царская постройка)
добавить районы Одессы()

**Comment by shitikovkirill** [comment]
Done
